### ISSUE TITLE
Restructure: Retire the 'require: {python-runtime, requirements}' contract

### ISSUE THREAD

**Issue by arjun024** [paketo-community/pip#83]
### Background
See [RFC 0001](https://github.com/paketo-community/python/blob/main/rfcs/0001-restructure.md) that outlines the proposed restructure of python family of buildpacks.

In https://github.com/paketo-community/pip/issues/82, this buildpack was made to support multiple contracts - requiring `cpython` per RFC 0001, and requiring {`python-runtime` + `requirements`} for backward compatibility.

### Proposal
* Remove {`python-runtime` + `requirements`} requirement to be full compliant to the RFC.
*  Buildpack API should be as follows:
   * provides: `pip`
   * requires: `cpython` during build

**Comment by fg-j** [comment]
@arjun024 or @emmjohnson is this still blocked?
